"""Add magic_jobs table for automated project imports

Revision ID: 5dca170b6de0
Revises: 5d35b6c1cf3a
Create Date: 2026-09-11 19:46:07.879189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dca170b6de0'
down_revision: Union[str, Sequence[str], None] = '5d35b6c1cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
